CREATE TABLE [MeDriAnchor].[GUIDSwap]
(
[NewID] BIGINT NULL,
[DBTableColumnID] BIGINT NOT NULL,
[GUID] UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT [PK_ApplicationOrigination_GUIDSwap] PRIMARY KEY CLUSTERED ([DBTableColumnID] ASC, [GUID] ASC)
);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_DBTableColumnID_NewID] ON [MeDriAnchor].[GUIDSwap]
(
	[DBTableColumnID] ASC,
	[NewID] ASC
)
WHERE ([NewID] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

